# Job config for phoenix-slurm

args:
  A: gts-vfung3
  N: 1
  t: "12:00:00"
  q: "inferno"
  C: "A100-80GB"
options:
  - "--gres=gpu:A100:1"
  - "--mem-per-gpu=80G"
  - "--mail-type=BEGIN,END,FAIL"
  - "--mail-user=sidharth.baskaran@gatech.edu"
