trainer: property

task:
  identifier: "mpnn_train_250"
  reprocess: False
  parallel: True
  seed: 0
  write_output: True
  parallel: True
  verbosity: 5

model:
  name: MPNN
  load_model: False
  save_model: True
  model_path: "mpnn_model.pth"
  edge_steps: 50
  self_loop: True
  # model attributes
  dim1: 100
  dim2: 100
  dim3: 100
  pre_fc_count: 1
  gc_count: 4
  post_fc_count: 3
  pool: "global_mean_pool"
  pool_order: "early"
  batch_norm: True
  batch_track_stats: True
  act: "relu"
  dropout_rate: 0.0

optim:
  max_epochs: 250
  max_checkpoint_epochs: 0
  lr: 0.001
  # Either custom or from torch.nn.functional library. If from torch, loss_type is TorchLossWrapper
  loss:
    loss_type: "TorchLossWrapper"
    loss_args: {"loss_fn": "l1_loss"}

  batch_size: 100
  optimizer:
    optimizer_type: "AdamW"
    optimizer_args: {}
  scheduler:
    scheduler_type: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

dataset:
  processed: False
  # Path to data files
  src: "data/test_data/raw/"
  target_path: "data/test_data/targets.csv"
  pt_path: "data/test_data/processed/"

  transforms:
    - name: GetY
      args:
        index: 0
      otf: False # Optional parameter, default is False
  # Format of data files (limit to those supported by ASE)
  data_format: "json"
  # Method of obtaining atom idctionary: available:(onehot)
  node_representation: "onehot"
  additional_attributes: []
  # Print out processing info
  verbose: True
  # Index of target column in targets.csv
  # graph specific settings
  cutoff_radius : 8.0
  n_neighbors : 12
  edge_steps : 50
  # Ratios for train/val/test split out of a total of 1
  train_ratio: 0.8
  val_ratio: 0.05
  test_ratio: 0.15
