trainer: property

task:
  name: "my_train_job"
  reprocess: False
  parallel: True
  seed: 0
  write_output: True
  verbosity: 5
  train_ratio: 0.8
  val_ratio: 0.05
  test_ratio: 0.15

model:
  name: CGCNN
  load_model: "False"
  save_model: "True"
  model_path: "my_model.pth"
  edge_steps: 50
  self_loop: True
  dim1: 100
  dim2: 150
  pre_fc_count: 1
  gc_count: 4
  post_fc_count: 3
  pool: "global_mean_pool"
  pool_order: "early"
  batch_norm: "True"
  batch_track_stats: "True"
  act: "relu"
  dropout_rate: 0.0

optim:
  max_epochs: 250
  lr: 0.002
  loss:
    loss_type: "DOSLoss"
    loss_args: {"loss_fn": "l1_loss", "scaling_weight": 0.05, "cumsum_weight": 0.005, "features_weight": 0.15}
  batch_size: 100
  optimizer:
    optimizer_type: "AdamW"
    optimizer_args: {}
  scheduler:
    scheduler_type: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

dataset:
  processed: False
  src: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/MP_data_npj/raw/"
  target_path: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/MP_data_npj/targets.csv"
  pt_path: "/global/homes/s/shuyijia/datasets/MP_data_npj/"
  data_format: "json"
  node_representation: "onehot"
  additional_attributes: ["features", "scaled", "scaling_factor"]
  verbose: "True"
  target_index: 0
  cutoff_radius : 8.0
  n_neighbors : 12
  edge_steps : 50
