# run_mode: chain

trainer: property

task:
  name: "my_train_job"
  reprocess: False
  parallel: True
  seed: 0
  write_output: True
  verbosity: 5

models:
  - model: DOSPredict
#    config_path: "configs/examples/DOSPredict_MP_data.yaml"
    config_path: "/global/cfs/projectdirs/m3641/Sarah/MatDeepLearn/configs/examples/DOSPredict_MP_data.yaml"
    run_mode: "train"
    seed: 0
  - model: CGCNN_CNN
#    config_path: "configs/examples/CGCNN_CNN_MP_data.yaml"
    config_path: "/global/cfs/projectdirs/m3641/Sarah/MatDeepLearn/configs/examples/CGCNN_CNN_MP_data.yaml"
    run_mode: "train"
    seed: 0
