trainer: property

task:
  # run_mode: train
  identifier: "cgcnn_vn-baseline"
  reprocess: False
  parallel: True
  seed: 0
  # seed=0 means random initalization
  write_output: True
  parallel: True
  # Training print out frequency (print per n number of epochs)
  verbosity: 1
  wandb:
    use_wandb: True
    wandb_entity: "fung-lab"
    wandb_project: "cgcnn_vn"
    notes: "Baseline with full MP"
    tags: ["baseline"]
    log_artifacts:
      - path: "/global/cfs/projectdirs/m3641/Sidharth/MatDeepLearn_dev/configs/examples/config_cgcnn_vn_opt.yml"
        name: "train config"
        type: "config"
      - path: "/global/cfs/projectdirs/m3641/Sidharth/MatDeepLearn_dev/matdeeplearn/models/cgcnn_vn.py"
        name: "cgcnn_vn model"
        type: "model"
    metadata:
      architecture: "CGCNN_VN"
      cluster: "perlmutter-slurm"
      dataset: "hMOF-5K"

model:
  name: CGCNN_VN
  load_model: False
  save_model: True
  model_path: "cgcnn_vn.pth"
  # model hyperparams
  hyperparams:
    edge_steps: 50
    self_loop: True
    dim1: 100
    dim2: 150
    atomic_intermediate_layer_resolution: 0
    pre_fc_count: 1
    gc_count: 4
    post_fc_count: 3
    pool: "global_mean_pool"
    virtual_pool: "AtomicNumberPooling"
    pool_choice: "virtual"
    node_pool_choice: "x_both"
    mp_pattern: ["x_both", "x_both", "x_both", "x_both"]
    pool_order: "early"
    batch_norm: True
    batch_track_stats: True
    act_fn: "relu"
    act_nn: "ReLU"
    dropout_rate: 0.0

optim:
  max_epochs: 500
  lr: 0.002
  loss:
    loss_type: "TorchLossWrapper"
    loss_args: {"loss_fn": "l1_loss"}
  batch_size: 100
  optimizer:
    optimizer_type: "AdamW"
    optimizer_args: {}
  scheduler:
    scheduler_type: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

dataset:
  processed: True # if False, need to preprocessor data and generate .pt file
  # Path to data files
  src: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/hMOF/raw_5k/data.json"
  # Path to target file within data_path
  target_path: ""
  # Path to save processed data.pt file
  pt_path: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/hMOF/raw_5k/"
  # transforms
  transforms:
    - name: GetY
      args:
        index: 5 # methane adsorption uptake
      otf: False
    - name: VirtualNodes
      args:
        virtual_box_increment: 3
        vv_cutoff: 6
        vv_neighbors: 50
        rv_cutoff: 6
        rv_neighbors: 50
        n_neighbors: 50
        cutoff: 5
        edge_steps: 50
      otf: False
  mp_nodes:
    - x
    - x_rv
    - x_vv
    - x_vr
    - x_both
  data_format: "json"
  node_representation: "onehot"
  additional_attributes: []
  # Print out processing info
  verbose: True
  # graph specific settings: preprocessing hyperparams
  preprocess_params:
    cutoff_radius : 5.0
    virtual_box_increment: 3
    n_neighbors : 50
    edge_steps : 50
  # Ratios for train/val/test split out of a total of 1
  train_ratio: 0.8
  val_ratio: 0.05
  test_ratio: 0.15
