simulation_type: NVT
timestep: 3
temperature: 1000
calculator_config_path: configs/calculator/config_pretrained_cgcnn.yml
total_steps: 100_000
log_console: False
save_metrics_per: 50_000
continue_simulation: False
state_path: train_outs/sim_records_107/one_mill_sim_cgcnn/atoms_state_at_step_1000.npz
save_metrics_folder: train_outs/sim_records_107/one_mill_sim_cgcnn
save_atomic_state_folder: train_outs/sim_records_107/one_mill_sim_cgcnn

device: cuda:3

force_mean: 0.5
force_std: 1.5


# alarms:
#   energy_diff: 0.4
#   rdf_diff: 2
#   min_dist: 1.3
#   max_dist: 2.5
  
