# hyperparameter sweep config for CGCNN_VN
method: random
metric:
    name: val_loss
    goal: minimize

parameters:
    virtual_box_increment: 
      min: 1.0
      max: 6.0
    rv_cutoff:
      min: 5.0
      max: 25.0
    rr_cutoff: 
      min: 5.0
      max: 25.0
    vr_cutoff:
      min: 5.0
      max: 25.0
    vv_cutoff:
      min: 5.0
      max: 25.0
