# hyperparameter sweep config for CGCNN_VN
method: random
metric:
    name: test_loss
    goal: minimize

parameters:
    # virtual_box_increment: 
    #   min: 1.0
    #   max: 5.0
    rv_cutoff:
      values: [5.0]
    rr_cutoff: 
      values: [5.0]
    # vr_cutoff:
    #   min: 5.0
    #   max: 12.0
    # vv_cutoff:
    #   min: 5.0
    #   max: 12.0
