trainer: property

task:
  # run_mode: train
  identifier: "my_train_job"
  reprocess: False
  parallel: True
  # seed=0 means random initalization
  seed: 0
  # Defaults to run directory if not specified
  # save_dir: "."
  # checkpoint_dir: "."
  write_output: True
  parallel: True
  #Training print out frequency (print per n number of epochs)
  verbosity: 5

model:
  name: dimenetplusplus
  load_model: False
  save_model: True
  model_path: "my_model.pth"
  edge_steps: 50
  self_loop: True
  # model attributes
  num_targets: 1
  use_pbc: False
  regress_forces: False
  hidden_channels: 128
  num_blocks: 4
  int_emb_size: 64
  basis_emb_size: 8
  out_emb_channels: 256
  num_spherical: 7
  num_radial: 6
  otf_graph: False
  cutoff: 8.0
  envelope_exponent: 5
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  num_post_layers: 1
  post_hidden_channels: 64
  pool: "global_mean_pool"
  activation: "relu"

optim:
  max_epochs: 400
  max_checkpoint_epochs: 0
  lr: 0.0005
  # Either custom or from torch.nn.functional library. If from torch, loss_type is TorchLossWrapper
  loss:
    loss_type: "TorchLossWrapper"
    loss_args: {"loss_fn": "l1_loss"}

  batch_size: 25
  optimizer:
    optimizer_type: "AdamW"
    optimizer_args: {}
  scheduler:
    scheduler_type: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

dataset:
  processed: False
  # Whether to use "inmemory" or "large" format for pytorch-geometric dataset. Reccomend inmemory unless the dataset is too large
  # dataset_type: "inmemory"
  # Path to data files
  #src: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/MP_data_69K/data.json"
  #src: "/project/Rithwik/MP_data_69K/raw/"
  src: "/project/Rithwik/MP_data_69K/data.json"
  # Path to target file within data_path
  #target_path: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/2D_data_npj/targets.csv"
  #target_path: "/project/Rithwik/MP_data_69K/targets.csv"
  target_path:
  # Path to save processed data.pt file
  #pt_path: "/global/cfs/projectdirs/m3641/Rithwik/datasets/MP_data_69K/"
  pt_path: "/project/Rithwik/MP_data_69K/"
  transforms:
    - name: GetY
      args:
        index: 0
      otf: True # Optional parameter, default is False
  all_neighbors : True
  # one of mdl, ase, ocp
  edge_calc_method: "mdl"
  # Format of data files (limit to those supported by ASE)
  data_format: "json"
  # Method of obtaining atom idctionary: available:(onehot)
  node_representation: "onehot"
  additional_attributes: []
  # Print out processing info
  verbose: True
  # Index of target column in targets.csv
  # graph specific settings
  preprocess_params:
    cutoff_radius : 8.0
    n_neighbors : 250
    num_offsets: 1
    edge_steps : 50
  # Ratios for train/val/test split out of a total of 1
  train_ratio: 0.8408
  val_ratio: 0.0764
  test_ratio: 0.0828
