trainer: property

task:
  # run_mode: train
  identifier: "my_train_job"
  reprocess: False
  parallel: True
  # seed=0 means random initalization
  seed: 0
  # Defaults to run directory if not specified
  # save_dir: "."
  # checkpoint_dir: "."
  write_output: True
  parallel: True
  #Training print out frequency (print per n number of epochs)
  verbosity: 5

model:
  name: gemnet_ocEarly
  load_model: False
  save_model: True
  model_path: "my_model.pth"
  edge_steps: 50
  self_loop: True
  # model attributes
  num_targets: 1
  num_spherical: 7
  num_radial: 6
  num_blocks: 4
  emb_size_atom: 128
  emb_size_edge: 128
  emb_size_trip_in: 128
  emb_size_trip_out: 64
  emb_size_trip: 64
  emb_size_quad_in: 64
  emb_size_quad_out: 64
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 16
  emb_size_cbf: 16
  emb_size_sbf: 16
  emb_size_bil_trip: 32
  num_before_skip: 1
  num_after_skip: 1
  num_concat: 1
  num_atom: 2
  num_output_afteratom: 1
  num_atom_emb_layers: 0
  num_global_out_layers: 2
  regress_forces: False
  direct_forces: False
  use_pbc: True
  scale_backprop_forces: False
  cutoff: 12.0
  cutoff_qint: 
  cutoff_aeaint: 
  cutoff_aint: 
  max_neighbors: 50
  max_neighbors_qint:
  max_neighbors_aeaint:
  max_neighbors_aint:
  rbf: {"name": "gaussian"}
  rbf_spherical:
  envelope: {"name": "polynomial", "exponent": 5}
  cbf: {"name": "spherical_harmonics"}
  sbf: {"name": "spherical_harmonics"}
  extensive: True
  forces_coupled: False
  output_init: "HeOrthogonal"
  activation: "silu"
  quad_interaction: False
  atom_edge_interaction: False
  edge_atom_interaction: False
  atom_interaction: False
  scale_basis: False
  qint_tags: [0, 1, 2]
  num_elements: 100
  otf_graph: True
  scale_file:
  num_post_layers: 3
  post_hidden_channels: 64
  pool: "global_mean_pool"
  act: "relu"

optim:
  max_epochs: 250
  max_checkpoint_epochs: 0
  lr: 0.0005
  # Either custom or from torch.nn.functional library. If from torch, loss_type is TorchLossWrapper
  loss:
    loss_type: "TorchLossWrapper"
    loss_args: {"loss_fn": "l1_loss"}

  batch_size: 100
  optimizer:
    optimizer_type: "AdamW"
    optimizer_args: {}
  scheduler:
    scheduler_type: "ReduceLROnPlateau"
    scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

dataset:
  processed: True
  # Path to data files
  src: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/2D_data_npj/raw/"
  # Path to target file within data_path
  target_path: "/global/cfs/projectdirs/m3641/Shared/Materials_datasets/2D_data_npj/targets.csv"
  # Path to save processed data.pt file
  pt_path: "/global/homes/r/rithwiks/datasets/2D_data_npj/"
  transforms:
    - name: GetY
      args:
        index: 0
      otf: True # Optional parameter, default is False
  # Format of data files (limit to those supported by ASE)
  data_format: "json"
  # Method of obtaining atom idctionary: available:(onehot)
  node_representation: "onehot"
  additional_attributes: []
  # Print out processing info
  verbose: True
  # Index of target column in targets.csv
  # graph specific settings
  cutoff_radius : 8.0
  n_neighbors : 250
  edge_steps : 50
  # Ratios for train/val/test split out of a total of 1
  train_ratio: 0.8
  val_ratio: 0.05
  test_ratio: 0.15
  all_neighbors : False
