simulation_type: NVT
timestep: 4
temperature: 2000
calculator_config_path: configs/calculator/config_pretrained_cgcnn.yml
total_steps: 50000
log_console: False
save_metrics_per: 50_000
continue_simulation: False
state_path: train_outs/sim_records_107/one_mill_sim_cgcnn_sam/atoms_state_at_step_1000.npz
save_metrics_folder: train_outs/sim_records_107/one_mill_sim_cgcnn_sam
save_atomic_state_folder: train_outs/sim_records_107/one_mill_sim_cgcnn_sam

device: cuda:3

# alarms:
#   energy_diff: 0.4
#   rdf_diff: 2
#   min_dist: 1.3
#   max_dist: 2.5
  
